### ISSUE TITLE
Obsługa błędu 'EOF' dla komend UI

### ISSUE THREAD

**Issue by arszonto** [IIS-ZPI/ZPI2020_zaoczni_Grupa_1#131]
Opis:
Podczas wykonywania testów manualnych, tester zgłosił błąd - aplikacja nie jest w stanie obsłużyć błędu typu 'EOF' w przypadku wprowadzanych komend. Należy wprowadzić niezbędne poprawki.

Kryteria akceptacji:
- [x] Wprowadzono obsługę błędu.
- [ ] Tester potwierdził, że wprowadzenie 'EOF' jako komendy jest poprawnie obsługiwane przez aplikację.

**Comment by arszonto** [comment]
@kubak95 przekazuję rozwiązanie do testów. Po zakończeniu testów opisz rezultaty i przypisz mi to zadanie ponownie.

**Comment by kubak95** [comment]
Poprawka nie przyniosła oczekiwanych rezultatów:


Traceback (most recent call last):
  File "/home/kuba/studia/Sem7/ZPI/ZPI2020_zaoczni_Grupa_1/run.py", line 4, in <module>
    app.run()
  File "/home/kuba/studia/Sem7/ZPI/ZPI2020_zaoczni_Grupa_1/app/Application.py", line 8, in run
    self.ui.listen_for_user_input()
  File "/home/kuba/studia/Sem7/ZPI/ZPI2020_zaoczni_Grupa_1/app/UserInterface.py", line 45, in listen_for_user_input
    self.handle_command(int(input("Wybierz numer komendy: ")))
  File "/home/kuba/studia/Sem7/ZPI/ZPI2020_zaoczni_Grupa_1/app/UserInterface.py", line 36, in handle_command
    result = CommandsList[commandNr-1].method(*args)
TypeError: show_ratio_changes() missing 3 required positional arguments: 'currency_one', 'currency_two', and 'timeframe'Traceback (most recent call last):
  File "/home/kuba/studia/Sem7/ZPI/ZPI2020_zaoczni_Grupa_1/run.py", line 4, in <module>
    app.run()
  File "/home/kuba/studia/Sem7/ZPI/ZPI2020_zaoczni_Grupa_1/app/Application.py", line 8, in run
    self.ui.listen_for_user_input()
  File "/home/kuba/studia/Sem7/ZPI/ZPI2020_zaoczni_Grupa_1/app/UserInterface.py", line 45, in listen_for_user_input
    self.handle_command(int(input("Wybierz numer komendy: ")))
  File "/home/kuba/studia/Sem7/ZPI/ZPI2020_zaoczni_Grupa_1/app/UserInterface.py", line 36, in handle_command
    result = CommandsList[commandNr-1].method(*args)
TypeError: show_ratio_changes() missing 3 required positional arguments: 'currency_one', 'currency_two', and 'timeframe'


Traceback (most recent call last):
  File "/home/kuba/studia/Sem7/ZPI/ZPI2020_zaoczni_Grupa_1/run.py", line 4, in <module>
    app.run()
  File "/home/kuba/studia/Sem7/ZPI/ZPI2020_zaoczni_Grupa_1/app/Application.py", line 8, in run
    self.ui.listen_for_user_input()
  File "/home/kuba/studia/Sem7/ZPI/ZPI2020_zaoczni_Grupa_1/app/UserInterface.py", line 45, in listen_for_user_input
    self.handle_command(int(input("Wybierz numer komendy: ")))
EOFError: EOF when reading a line

**Comment by arszonto** [comment]
@kubak95 nowy fix jest dostępny tutaj: bugfix/131-obsluga-bledu-eof-dla-komend-UI-2

**Comment by kubak95** [comment]
Przetestowana zmiana nie powoduje zatrzymania aplikacji, rozwiązanie spełnia wymagania
